name: ci

on: pull_request

jobs:
  testes_de_integridade:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      
      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Instalar dependências Playwright
        run: npx playwright install --with-deps

      - name: Instalar browsers Playwright
        run: npx playwright install chromium

      - name: Executar testes
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/testdb
        run: poetry run task test
