name: ci

on: pull_request

jobs:
    testes_de_integridade:
        runs-on: ubuntu-latest

        steps:
            - name: Baixar o repositório
              uses: actions/checkout@v4 # Baixa o meu repositório git

            - name: Entrar no repositório
              run: echo $(ls) #cd project_and_process # Baixa o meu repositório git

            - name: Instalar o python
              uses: actions/setup-python@v5
              with:
                python-version: '.python-version'

            - name: Instalar poetry
              run: pip install poetry

            - name: Instalar dependencias
              run: poetry install

            - name: Executar testes
              run: task test